sudo: required
services:
  - docker
  
language: java
# use Java 8
jdk:
- openjdk8

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
script: 
  - mvn clean test 
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME_API_SERVICE=surenraju/api-service
  - docker build -f $TRAVIS_BUILD_DIR/Dockerfile.api-service -t $IMAGE_NAME_API_SERVICE:$COMMIT $TRAVIS_BUILD_DIR
  - docker tag $IMAGE_NAME_API_SERVICE:$COMMIT $IMAGE_NAME_API_SERVICE:$TAG
  - docker push $IMAGE_NAME_API_SERVICE
  - export IMAGE_NAME_INIT_SERVICE=surenraju/api-service
  - docker build -f $TRAVIS_BUILD_DIR/Dockerfile.init-service -t $IMAGE_NAME_INIT_SERVICE:$COMMIT $TRAVIS_BUILD_DIR
  - docker tag $IMAGE_NAME_INIT_SERVICE:$COMMIT $IMAGE_NAME_INIT_SERVICE:$TAG
  - docker push $IMAGE_NAME_INIT_SERVICE

after_success :
    - echo Post build activities