sudo: required
services:
  - docker
  
language: java
# use Java 8
jdk:
- openjdk8


# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
script: 
  - mvn clean install 
  - echo $TRAVIS_BUILD_DIR

after_success :
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=surenraju/api-service
  - echo $TRAVIS_BUILD_DIR
  - echo $TAG
  - echo $IMAGE_NAME
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME