
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: web
    servicePort: 8080
          

---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apiservice
  type: NodePort
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  selector:
    matchLabels:
      app: apiservice
  replicas: 3
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: surenraju/apiservice
        env:
          # Use secret in real usage
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/titanic
        - name: SPRING_DATASOURCE_USERNAME
          value: titanic
        - name: SPRING_DATASOURCE_PASSWORD
          value: Pass1234
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: user-service
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1  