apiVersion: batch/v1
kind: Job
metadata:
  name: apiinitjob
spec:
  template:
    spec:
      containers:
      - name: apiinitjob
        image: surenraju/api-init-service
        env:
          # Use secret in real usage
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/titanic
        - name: SPRING_DATASOURCE_USERNAME
          value: titanic
        - name: SPRING_DATASOURCE_PASSWORD
          value: Pass1234
      restartPolicy: Never
  backoffLimit: 4