version: "3"

networks:
  default:
    driver: bridge
    
services:
  mysql:
    image: mysql
    image: mysql:5.7.19
    hostname: mysql
    command: ["--server-id=1"]
    environment:
      - MYSQL_ROOT_PASSWORD=Pass1234
    volumes:
      - ${DOCKER_IMPORTS}/mysql-base/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DOCKER_IMPORTS}/mysql-base/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
      - ${DOCKER_EXPORTS}/mysql/current/data/:/var/lib/mysql/:delegated
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - mysql
          
  api-service:
    build:
      context: ../api-service
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/titanic
      SPRING_DATASOURCE_USERNAME: titanic
      SPRING_DATASOURCE_PASSWORD: Pass1234    
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - api-service
          
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis